### ISSUE TITLE
Teams Modification API allows unknown User Ids to be added and saved.

### ISSUE THREAD

**Issue by hcornelison** [OctopusDeploy/OctopusClients#337] opened 2018-10-29 16:57 UTC
I'm writing some custom code using the latest Octopus.Client C# NuGet Package. I created a new Service Account User, created an API Key for it, and then attempted to add the user to a specific Team. I accidentally added the Team's Id string instead of the new Users Id to the list of MemberUserIds. When I called the Teams.Modify method, it saved the Team with an incorrect Id.

Whenever you open the Octopus Web Interface, it tells me that I now have more members in the Team that what it actually does. I found in the OctopusDeploy database, in the Teams table, that the Team Id was added, causing the Web Interface to think there were more members than there really were.

Should this method validate that the User Id you are trying to add actually exists before persisting the data to the database?

**Comment by hcornelison** [comment] 2018-10-29 17:05
Here is a simple example that reproduces the issue.

```
using Octopus.Client;

namespace OctopusDeployApiManagement
{
   class Program
   {
      private const string ApiKey          = "API-MySuperSecretApiKey";
      private const string OctopusServer   = "http://localhost/OctopusDeploy";
      private static readonly OctopusRepository _octopus = new OctopusRepository(new OctopusServerEndpoint(OctopusServer, ApiKey));

      static void Main()
      {
         //Create a new Octopus Deploy User
         var newUser = _octopus.Users.CreateServiceAccount("Test", "Test");
         
         //Generate a new API Key for new user
         var key = _octopus.Users.CreateApiKey(newUser, "Test");

         //Find the team I want to modify.
         var team = _octopus.Teams.FindOne(resource => resource.Name == "Test Team");

         //ISSUE:
         //Incorrectly passed in the Team's Id string itself instead of the users Id.
         team.MemberUserIds.Add(team.Id);

         //Save the Team
         _octopus.Teams.Modify(team);
      }
   }
}
```

This leads to the Octopus Deploy web interface stating that there are an incorrect number of users in the Team, the User itself is not part of the team, and without manipulating the database directly, you cannot rectify this any other way through the product.

**Comment by TomPeters** [comment] 2018-11-01 22:15
Hi,

Thanks for reporting this! This is definitely a bug, and we should be validating that the User id exists before allowing this request to complete. Interestingly, it only works because you happened to pass in the Id of a document that does actually exist in the database (the team). So we do have some validation around this area, but it is clearly insufficient.

Since this is actually a bug on the Octopus Server (not a bug with the C# Client), I am going to close this issue. I have created a separate issue in our Octopus Server Issues repository which you can find [here](https://github.com/OctopusDeploy/Issues/issues/5049).

**Closed by TomPeters** 2018-11-01 22:15 UTC
