### ISSUE TITLE
Using octo.exe pack with an extension-less file does not add file to nuget

### ISSUE THREAD

**Issue by danspam** [OctopusDeploy/OctopusClients#94] opened 2016-11-04 08:37 UTC
If you run `octo.exe pack id=something` on a directory that has a file without an extension, it is not added to the nuget package. This is confirmed by inspecting the package afterwards with Nuget Package Explorer. 

I found that the only way I could add such a file to my package was to add it to the package manually using Nuget Package explorer.

**Comment by droyad** [comment] 2016-11-11 00:27
@danspam Thanks for reporting that, however I can't reproduce it using Octo 3.5.4 or 4.0.3. Which version are you using?

I have 2 files in a directory `out` and `out.txt` and when I run `Octo.exe pack -id=foo` from that directory both files appear in the nupkg.

**Comment by danspam** [comment] 2016-11-11 00:40
Just tried again, with everything I did in once picture. Perhaps this helps narrow down what I am doing wrong?

![octotest](https://cloud.githubusercontent.com/assets/239976/20200156/1db93072-a7fb-11e6-9699-ad3acd5378f3.png)

**Comment by droyad** [comment] 2016-11-11 09:01
I was able to reproduce what you saw. However the file is in the `nupkg` if it is opened using a zip program. Also I was able to deploy the package with Octopus and the extensionless file was deployed.

@danspam When you don't manually add the file, does it getting deployed for you?

**Comment by danspam** [comment] 2016-11-12 00:57
Interesting. You are correct, it does appear when you open it in a zip program. This all stems from when I deployed a nuget package that I had created using this method with Octopus Deploy and the extension-less file did not appear on the server. I had uploaded it to the Library and deployed it with a standard step - internal nuget feed etc..

**Comment by droyad** [comment] 2016-12-08 22:27
Closing this as the file gets added to the pupkg. If there is still a problem unpacking it with octopus, please drop Octopus support a line and we will look at it in the main product.

**Closed by droyad** 2016-12-08 22:27 UTC
